---
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# Practicalli Rust
site_name: Practicalli Rust
site_url: https://practical.li/rust
site_description: Practical guide to Rust programming language
site_author: Practicalli
site_org: https://practical.li/
copyright: Copyright &copy 2023  Practicali <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
repo_url: https://github.com/practicalli/rust/
edit_uri: https://github.com/practicalli/rust/edit/main/docs/

# Deployment
# remote_name: origin
remote_branch: gh-pages # deployment branch

# Theme and styling
theme:
  name: material
  logo: assets/images/practicalli-logo.png
  favicon: assets/favicon.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes # Nav sections can have files
    - navigation.instant # Avoid page reloading for internal links
    - navigation.top
    - navigation.tracking # Update URL with sub-heading anchor names
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  # Override theme
  custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css

## Additional styling
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html # Grids
  - footnotes # footnotes and abbreviations
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys # keyboard keys
  - pymdownx.magiclink
  - def_list # lists
  - pymdownx.tasklist:
      custom_checkbox: true # checkboxes
  - toc:
      permalink: λ︎

## Plugins
plugins:
  # Explicitly add search plugin when defining plugins in this configuration file
  - search
  - callouts
  - glightbox # Image aligning
  - git-revision-date-localized: # Update and Creation date of each page
      # enable_creation_date: true
      fallback_to_build_date: true

  # Generate Social Cards via CI only
  # in assets/images/social
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS_GENERATE, true]

  # Redirect pages when moved or changed
  # - redirects:
  #     redirect_maps:
  #       repl-driven-development.md: introduction/repl-workflow.md

# Footer / Social Media
extra:
  analytics:
    provider: google
    property: G-QZ22Z9DH4T
  social:
    - icon: material/web
      link: https://practical.li/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jr0cket/
    - icon: fontawesome/brands/slack
      link: https://clojurians.slack.com/messages/practicalli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/practical_li
    - icon: fontawesome/brands/github
      link: https://github.com/practicalli
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/practicalli

# Navigation
nav:
  - Introduction:
      - index.md
      - Rust in Fifteen Mins: introduction/rust-in-15-minutes.md
      - Rust Workflow: introduction/rust-workflow.md
      - Functional Concepts: introduction/functional-concepts.md
      - Contributing: https://practical.li/contributing/
      - Writing Tips: https://practical.li/writing-tips/
  - Install:
      - install/index.md
  - Editors:
      - editors/index.md
      - editors/neovim.md
  - Rust Projects:
      - projects/index.md
      - Guides:
          - projects/guides/index.md
          - Rest API: projects/guides/rest-api.md
  - Code Challenges:
      - coding-challenges/index.md
      - Exercism:
          - coding-challenges/exercism/index.md
          - RNA Transcription: coding-challenges/exercism/rna-transcription.md
          - Nucleotide Count: coding-challenges/exercism/nucleotide-count.md
          - coding-challenges/exercism/hamming.md
          - coding-challenges/exercism/space-age.md
      - TDD Kata:
          - simple-projects/tdd-kata/index.md
          - Recent Song list: simple-projects/tdd-kata/recent-song-list.md
          - Salary Slip Generator: simple-projects/tdd-kata/salary-slip-generator.md
          # - simple-projects/split-the-bill.md
      - Games:
          - games/index.md
          - TicTacToe:
              - games/tictactoe-cli/index.md

  - Testing:
      - testing/index.md
      - Unit Testing:
          - testing/unit-testing/index.md
          - Writing Tests: testing/unit-testing/writing-unit-tests.md
          - Fixtures: testing/unit-testing/fixtures.md
          - Test Selectors: testing/unit-testing/test-selectors.md
      - Test runners:
          - testing/test-runners/index.md
  - Continuous Integration:
      - continuous-integration/index.md
      - GitHub Workflow:
          - continuous-integration/github-workflow/index.md

  - Reference:
      - reference/index.md
      - Books: reference/books.md
